# -*- coding: utf-8 -*-
"""preprocessing3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13r7nr6vt-ojfXdPHlQMNGGZ-YpLLNRX1
"""

# Libary
import re
import string
import unicodedata
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from langdetect import detect, LangDetectException

# Download resource NLTK (jalankan sekali)
def download_nltk_resources():
    for r in ["punkt", "stopwords", "punkt_tab"]:
        try:
            nltk.download(r, quiet=True)
        except Exception:
            pass

download_nltk_resources()

# Konstanta

# Pola regex (hanya yang relevan untuk pure teks)
PATTERN_URL   = re.compile(r'https?://\S+|www\.\S+')
PATTERN_EMAIL = re.compile(r'\b[\w.+-]+@[\w-]+\.[a-z]{2,}\b', re.IGNORECASE)

# Angka dipertahankan secara default (misal "tahun 1945", "pasal 33")
# tapi bisa dinonaktifkan lewat parameter
PATTERN_NUMBER = re.compile(r'\b\d+\b')

# Stopword tambahan  slang akademik & singkatan umum
EXTRA_STOPWORDS_ID = {
    "yaitu", "yakni", "misalnya", "contoh", "seperti", "antara", "lain",
    "dll", "dsb", "dst", "tsb", "yg", "dg", "dgn", "utk", "dlm",
    "thd", "thdp", "krn", "krna", "karna", "sbg", "sbgai", "spt",
    "tsb", "svp", "jd", "jadi", "jika", "maka",
}

EXTRA_STOPWORDS_EN = {
    "etc", "eg", "ie", "vs", "versus", "also", "well",
}


#Kelas Utama

class TextPreprocessor:
    """
    Preprocessor bilingual (Indonesia + Inggris) untuk essay grading.
    Dirancang untuk mapel pure teks (non-eksakta).

    Parameter
    ---------
    remove_stopwords : bool
        Aktifkan penghapusan stopword (default True).
    do_stemming : bool
        Aktifkan stemming (default True).
    keep_numbers : bool
        Pertahankan angka dalam teks — berguna untuk konteks sejarah,
        IPS, PKn, dll. (default True).
    min_token_len : int
        Panjang minimum token yang dipertahankan (default 2).
    """

    def __init__(
        self,
        remove_stopwords: bool = True,
        do_stemming: bool = True,
        keep_numbers: bool = True,
        min_token_len: int = 2,
    ):
        self.remove_stopwords = remove_stopwords
        self.do_stemming = do_stemming
        self.keep_numbers = keep_numbers
        self.min_token_len = min_token_len

        # Stemmer Indonesia (PySastrawi)
        self.stemmer_id = StemmerFactory().create_stemmer()

        # Stemmer Inggris (NLTK Porter)
        self.stemmer_en = PorterStemmer()

        # Stopword Indonesia
        sw_id = set(StopWordRemoverFactory().get_stop_words()) | EXTRA_STOPWORDS_ID
        self.stopwords_id = sw_id

        # Stopword Inggris
        sw_en = set(stopwords.words("english")) | EXTRA_STOPWORDS_EN
        self.stopwords_en = sw_en

        # Gabungan (fallback jika bahasa tidak terdeteksi)
        self.stopwords_combined = sw_id | sw_en

    # Deteksi bahasa

    def detect_language(self, text: str) -> str:
        """Return 'id', 'en'. Default fallback ke 'id'."""
        try:
            lang = detect(text)
            return lang if lang in ("id", "en") else "id"
        except LangDetectException:
            return "id"

    # Step 1: Normalisasi Unicode

    def normalize_unicode(self, text: str) -> str:
        """Normalisasi karakter unicode ke bentuk standar (NFKC)."""
        return unicodedata.normalize("NFKC", text)

    #  Step 2: Hapus URL & email

    def remove_urls_emails(self, text: str) -> str:
        """Hapus URL dan alamat email — tidak informatif untuk konten esai."""
        text = PATTERN_URL.sub(" ", text)
        text = PATTERN_EMAIL.sub(" ", text)
        return text

    # Step 3: Lowercase

    def to_lowercase(self, text: str) -> str:
        return text.lower()

    # Step 4: Hapus tanda baca & noise

    def remove_noise(self, text: str) -> str:
        """
        Hapus tanda baca dan karakter tidak relevan.
        Pertahankan tanda hubung di dalam kata majemuk (misal: tari-tarian).
        """
        # Hapus karakter kontrol
        text = re.sub(r'[\x00-\x1f\x7f]', ' ', text)

        # Hapus tanda baca kecuali tanda hubung
        allowed = string.punctuation.replace('-', '')
        text = re.sub(f'[{re.escape(allowed)}]', ' ', text)

        # Hapus tanda hubung yang tidak mengapit huruf (bukan kata majemuk)
        text = re.sub(r'(?<![a-zA-Z])-|-(?![a-zA-Z])', ' ', text)

        # Hapus angka jika keep_numbers=False
        if not self.keep_numbers:
            text = PATTERN_NUMBER.sub(' ', text)

        # Bersihkan whitespace berlebih
        text = re.sub(r'\s+', ' ', text).strip()

        return text

    # Step 5: Tokenisasi

    def tokenize(self, text: str) -> list:
        return word_tokenize(text)

    # Step 6: Hapus stopword

    def remove_stopword_tokens(self, tokens: list, lang: str) -> list:
        if not self.remove_stopwords:
            return tokens

        sw = {
            "id": self.stopwords_id,
            "en": self.stopwords_en,
        }.get(lang, self.stopwords_combined)

        return [t for t in tokens if t not in sw]

    # Step 7: Stemming

    def stem_tokens(self, tokens: list, lang: str) -> list:
        if not self.do_stemming:
            return tokens

        result = []
        for token in tokens:
            # Jangan stem angka
            if token.isdigit():
                result.append(token)
            elif lang == "en":
                result.append(self.stemmer_en.stem(token))
            else:
                result.append(self.stemmer_id.stem(token))
        return result

    # Step 8: Filter token pendek

    def filter_short_tokens(self, tokens: list) -> list:
        return [t for t in tokens if len(t) >= self.min_token_len]

    # Pipeline Utama

    def full_pipeline(self, text: str, return_tokens: bool = False):
        """
        Jalankan seluruh pipeline preprocessing.

        Parameter
        ---------
        text         : str  — teks mentah (jawaban siswa atau kunci jawaban)
        return_tokens: bool — True = return list, False = return string

        Return
        ------
        str atau list, tergantung return_tokens.
        """
        if not text or not text.strip():
            return [] if return_tokens else ""

        lang  = self.detect_language(text)
        text  = self.normalize_unicode(text)
        text  = self.remove_urls_emails(text)
        text  = self.to_lowercase(text)
        text  = self.remove_noise(text)
        tokens = self.tokenize(text)
        tokens = self.remove_stopword_tokens(tokens, lang)
        tokens = self.stem_tokens(tokens, lang)
        tokens = self.filter_short_tokens(tokens)

        return tokens if return_tokens else " ".join(tokens)

    # Info / Debug

    def get_info(self, text: str) -> dict:
        """
        Return metadata preprocessing untuk keperluan debugging & analisis.
        Berguna saat rekan data science ingin inspect hasil pipeline.
        """
        lang = self.detect_language(text)
        tokens_raw = word_tokenize(text.lower())
        tokens_processed = self.full_pipeline(text, return_tokens=True)

        return {
            "detected_language"    : lang,
            "original_char_length" : len(text),
            "raw_token_count"      : len(tokens_raw),
            "processed_token_count": len(tokens_processed),
            "processed_tokens"     : tokens_processed,
            "processed_text"       : " ".join(tokens_processed),
        }


#Fungsi Utilitas

def batch_preprocess(texts: list, preprocessor: TextPreprocessor = None, **kwargs) -> list:
    """
    Preprocessing untuk list teks sekaligus.
    Dipakai saat rekan data science loading dataset CSV.

    Contoh:
        results = batch_preprocess(df["student_answer"].tolist())
    """
    if preprocessor is None:
        preprocessor = TextPreprocessor(**kwargs)
    return [preprocessor.full_pipeline(t) for t in texts]


def compare_texts(text_a: str, text_b: str, preprocessor: TextPreprocessor = None) -> dict:
    """
    Bandingkan dua teks setelah preprocessing.
    Menghitung Jaccard similarity sebagai baseline cepat —
    berguna untuk sanity check sebelum model dilatih.
    """
    if preprocessor is None:
        preprocessor = TextPreprocessor()

    tokens_a = set(preprocessor.full_pipeline(text_a, return_tokens=True))
    tokens_b = set(preprocessor.full_pipeline(text_b, return_tokens=True))

    intersection = tokens_a & tokens_b
    union = tokens_a | tokens_b
    jaccard = len(intersection) / len(union) if union else 0.0

    return {
        "text_a_processed" : " ".join(tokens_a),
        "text_b_processed" : " ".join(tokens_b),
        "common_tokens"    : sorted(intersection),
        "jaccard_similarity": round(jaccard, 4),
    }

# Quick Test
if __name__ == "__main__":
    prep = TextPreprocessor()

    test_cases = [
        # Sejarah / IPS
        "Proklamasi kemerdekaan Indonesia dibacakan oleh Soekarno dan Hatta pada tanggal 17 Agustus 1945 di Jakarta.",
        # PKn
        "Pancasila merupakan dasar negara dan ideologi bangsa Indonesia yang terdiri dari lima sila.",
        # Bahasa Indonesia
        "Teks narasi adalah jenis teks yang menceritakan suatu peristiwa atau kejadian secara runtut dan kronologis.",
        # Bahasa Inggris
        "Democracy is a system of government in which citizens exercise power by voting in free and fair elections.",
        # Campuran Indo-Inggris
        "Good governance adalah tata kelola pemerintahan yang baik, transparan, dan akuntabel kepada masyarakat.",
    ]

    print("=" * 65)
    print("  TEST PREPROCESSING — Essay Grader (Pure Text Mode)")
    print("=" * 65)

    for i, teks in enumerate(test_cases, 1):
        info = prep.get_info(teks)
        print(f"\n[Test {i}]")
        print(f"Input  : {teks}")
        print(f"Bahasa : {info['detected_language']}")
        print(f"Token  : {info['raw_token_count']} → {info['processed_token_count']}")
        print(f"Output : {info['processed_text']}")

    print("\n" + "=" * 65)
    print("  TEST compare_texts")
    print("=" * 65)
    a = "Pancasila adalah dasar negara Indonesia yang memiliki lima sila"
    b = "Pancasila merupakan ideologi dan dasar negara Republik Indonesia terdiri dari 5 sila"
    hasil = compare_texts(a, b, prep)
    print(f"\nTeks A : {a}")
    print(f"Teks B : {b}")
    print(f"Kata sama   : {hasil['common_tokens']}")
    print(f"Jaccard sim : {hasil['jaccard_similarity']}")